var PopUpText;
var allStrings;
var livingCostsPP = 3;
var currentEvent;
var turnCount = 1;
var poorEventCounter = 10;
var playerActivity = [1,1,1,1,1,1,1,1,1,1];
var score = 0;
var playerName = "_";
var newscore = 0;
var leaveFarmReward = 0;
var leaveFarmPointsAwarded = 0;
var marriagePointsRewarded = 2;
var leaveFarmBaby = 420;
var leaveFarmChildNoEd = 9999;
var leaveFarmChildEd = 69420;
var leaveFarmAdultNoEd = 99999;
var leaveFarmAdultSomeEd = 9999;
var leaveFarmAdultHighEd = 999999999;
var longTimeEffectChemical;
var longTimeEffectOpium;
var longTimeEffectParamilitary;
var effectAffectuatedChemical;
var effectAffectuatedOpium;
var effectAffectuatedParamilitary;
var familyMemberDied;
var starvation;
var childBornThisYear = false;
var clinicBuilt = false;
var schoolBuilt = false;
var infrastructureBuilt = false;
var communicationsBuilt = false;
var representativeBuilt = false;
var insuranceBuilt = false;
var numberOfProjectsBuilt = 0;
road._visible = false;
communicationsGraphic._visible = false;
schoolGraphic._visible = false;
clinicGraphic._visible = false;
representativeGraphic._visible = false;
insuranceGraphic._visible = false;
projectInfoBox._visible = false;
var whoDiedFromLowHealth = "";
var startMoney = 420;
var maxMoney = 300;
var minMoney = 1;
var brokeEarningChemical = 9999;
var brokeEarningTribalDance = 9999;
var brokeEarningOpium = 9999;
var brokeEarningParamilitary = 9999;
var brokeEarningCityMigrate = 9999;
var newWifeDowryEarning = 9999;
var schoolFee = 400;
var cornPrice = Math.floor(Math.random(1) * 9) + 5;
var cornMultiplier = 11;
var wheatPrice = 13;
var wheatMultiplier = 13;
var cottonPrice = 15;
var cottonMultiplier = 16;
var peanutPrice = 5;
var peanutMultiplier = 55;
var poppyPrice = 0;
var poppyMultiplier = 20;
var poppyAmount = 50;
var chickenPrice = 69;
var chickenMultiplier = 8;
var pigPrice = 69;
var pigMultiplier = 15;
var cowPrice = 69;
var cowMultiplier = 40;
var elephantPrice = 69;
var elephantMultiplier = 120;
var shovelPrice = 25;
var shovelMultiplier = 0.1;
var scythePrice = 35;
var scytheMultiplier = 0.15;
var plowPrice = 69;
var plowMultiplier = 0.4;
var tractorPrice = 69;
var tractorMultiplier = 0.8;
var harvesterPrice = 69;
var harvesterMultiplier = 1;
var shedPrice = 69;
var shedMultiplier = 0.1;
var wellPrice = 69;
var wellMultiplier = 0.15;
var barnPrice = 69;
var barnMultiplier = 0.9;
var communicationsPrice = 69;
var infrastructurePrice = 69;
var schoolPrice = 69;
var clinicPrice = 69;
var representativePrice = 69;
var insurancePrice = 69420;
var communicationsDependency = [0];
var infrastructureDependency = [0];
var schoolDependency = [0];
var clinicDependency = [0];
var representativeDependency = [0];
var insuranceDependency = ["representative"];
var communicationsMultiplier = 0;
var infrastructureMultiplier = 0;
var schoolMultiplier = 0;
var clinicMultiplier = 0;
var representativeMultiplier = 0;
var insuranceMultiplier = 0;
var cornDependency = [0];
var wheatDependency = [0];
var cottonDependency = [0];
var peanutDependency = [0];
var poppyDependency = [0];
var chickenDependency = ["shed"];
var pigDependency = ["shed","well"];
var cowDependency = ["barn","well"];
var elephantDependency = ["barn","well"];
var shovelDependency = [0];
var scytheDependency = [0];
var plowDependency = [0];
var tractorDependency = [0];
var harvesterDependency = [0];
var shedDependency = [0];
var wellDependency = [0];
var barnDependency = [0];
var Choises = ["Nothing","corn","wheat","cotton","peanut","poppy","chicken","pig","cow","elephant","shovel","scythe","plow","tractor","harvester","shed","well","barn","communications","infrastructure","school","clinic","representative","insurance"];
var sellChickenPrice;
var sellPigPrice;
var sellCowPrice;
var sellElephantPrice;
var sellWellPrice;
var sellShedPrice;
var sellBarnPrice;
var sellShovelPrice;
var sellScythePrice;
var sellPlowPrice;
var sellTractorPrice;
var sellHarvesterPrice;
var sellChickenAvail = 0;
var sellPigAvail = 0;
var sellCowAvail = 0;
var sellElephantAvail = 0;
var sellWellAvail = 0;
var sellShedAvail = 0;
var sellBarnAvail = 0;
var sellShovelAvail = 0;
var sellScytheAvail = 0;
var sellPlowAvail = 0;
var sellTractorAvail = 0;
var sellHarvesterAvail = 0;
var IOcornAmount = 0;
var IOwheatAmount = 0;
var IOcottonAmount = 0;
var IOpeanutAmount = 0;
var IOpoppyAmount = 0;
var IOchickenAmount = 0;
var IOpigAmount = 0;
var IOcowAmount = 0;
var IOelephantAmount = 0;
var IOcornYield = 0;
var IOwheatYield = 0;
var IOcottonYield = 0;
var IOpeanutYield = 0;
var IOpoppyYield = 0;
var IOchickenYield = 0;
var IOpigYield = 0;
var IOcowYield = 0;
var IOelephantYield = 0;
var IOtoolsBonus = "15 %";
var IOcropsTotal = 0;
var IObuildingBonus = "15 %";
var IOlivestockTotal = 0;
var IOsum = 0;
var IOworkload = "140 %";
var IOtotal = 0;
var IOeventModifierNumber = 0;
var IOeventModifier = "100 %";
var IOcalcString = "Income this year<br>(calculation here):";
var IOsavedfromlastyear = 0;
var IOlivingCosts = 0;
var IOtotalFinal = 0;
var reasonForGameEnd = "everyoneDied";
var totalSchoolCount = 0;
var totalBabyCount = 0;
var totalMarriageCount = 0;
var farmModel = mvcFarm.FarmModel.getModel();
var farmTraceView = new mvcFarm.FarmTraceView(farmModel,farmController);
var farmGraphicView = new mvcFarm.FarmGraphicView(farmModel,farmController);
var farmInfoBoxView = new mvcFarm.FarmInfoBoxView(farmModel,farmController);
var farmController = new mvcFarm.FarmController(farmModel);
farmModel.addObserver(farmTraceView);
farmModel.addObserver(farmGraphicView);
farmModel.addObserver(farmInfoBoxView);
farmController.newGame();
farmController.initNotify();
